### ISSUE TITLE
%compare - library compare currently not working

### ISSUE THREAD

**Issue by KatjaGlassConsulting** [scottbass/SAS#1]
Hi, it seems that with the change of 13Sep (rename parameter compare to comp), the library compare is no longer working. The library example in the header does not create any output.

**Comment by scottbass** [comment]
The fix was to change:
libname="&base"
to
upcase(libname)="%upcase(&base)"

(and same for &comp)

when creating the workspde.compare_libraries dataset.

I'm not sure why the previous rename of compare= to comp= parameter regressed the code, but it should be fixed now.  Please re-test and reopen this issue if required.

Thank you for reporting this issue.
